#!/bin/bash

ITEM_COLOR_COLOR=183996

export TRANSPARENT=0x206889e6

export ITEM_COLOR=0xff$ITEM_COLOR_COLOR
export ACCENT_COLOR=0xffba6016
export SECONDARY_ITEM_COLOR=$ACCENT_COLOR

export BAR_COLOR=0x17$ITEM_COLOR_COLOR

export BACKGROUND_BORDER_COLOR=

export WINDOW_BORDER_COLOR=$ACCENT_COLOR
