#!/bin/bash

export TRANSPARENT=0x0cffffff

export ITEM_COLOR=0xff000000
export ACCENT_COLOR=0xffc3c6cb
export SECONDARY_ITEM_COLOR=$ACCENT_COLOR

export BAR_COLOR=0x88000000

export BACKGROUND_BORDER_COLOR=

export WINDOW_BORDER_COLOR=$ACCENT_COLOR
