#!/bin/bash

export TRANSPARENT=0x207357c2

export ITEM_COLOR=0xff011627
export ACCENT_COLOR=0xff8367d2
export SECONDARY_ITEM_COLOR=0xaaf7c2ff

# Optional
export BAR_COLOR=

# Optional
export BACKGROUND_BORDER_COLOR=

export WINDOW_BORDER_COLOR=$ACCENT_COLOR

