#!/bin/bash

export TRANSPARENT=0x0c

export ITEM_COLOR=0xff
export ACCENT_COLOR=0xff
export SECONDARY_ITEM_COLOR=$ACCENT_COLOR

# Optional
export BAR_COLOR=

# Optional
export BACKGROUND_BORDER_COLOR=

export WINDOW_BORDER_COLOR=0xffe2e2e3

